name: Ko イメージの公開

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  KO_DOCKER_REPO: ghcr.io/${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Go のセットアップ
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Ko のインストール
        uses: ko-build/setup-ko@v0.6

      - name: GHCRにログイン
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ko でビルドとプッシュ
        run: ko build --platform=linux/amd64 --bare